### ISSUE TITLE
GHAzDO scanning results are not being cleared properly from Advanced Security tab

### ISSUE THREAD

**Issue by hchendow** [microsoft/GHAzDO-Resources#49]
Greetings,

I'm having a peculiar issue with some repos that have had a scan done in the past (March) and now when I run it again the vulnerabilities that are resolved in the Pull Request are not being cleared in the main branch after merging. I have confirmed multiple times that running the scan manually does not change this. 

This image shows the results of the dependency scan which only shows 22 medium vulnerabilities.
![image](https://github.com/user-attachments/assets/87f538bc-f5b3-443f-aaf7-c34e73a5fe2e)

Then when you look at the dependency scanning results in the Advanced Security tab in DevOps, we still have the critical and high vulnerabilities that have already been addressed,
![image](https://github.com/user-attachments/assets/6c029a41-54c7-4160-82c3-5b94ba51b109)

This is happening for both dependency and code scanning. In addition, Pull Request and branch scan results don't see to appear in the Advanced Security tab either - only the main branch. 
 
Any insight and help with correcting this will be greatly appreciated.

**Comment by laurajjiang** [comment]
Hi @hchendow - I think this has been talked through in a couple of different avenues. Just to close the conversation, this is due to how alert fingerprints are created and tied to a pipeline definition. The recommendation for now is to separate changes to the pipeline with code changes relative to Advanced Security alerts. Our team will look into, long-term, solutions here as I understand this can be painful to deal with multiple times.

Pull request results should now be properly shown in the Advanced Security repository context via the branch picker with a separation for PR branches versus non-PR branches.
